### ISSUE TITLE
Talkinghead/live2d not appearing in SillyTavern

### ISSUE THREAD

**Issue by SmoothBrainApe** [SillyTavern/SillyTavern-extras#142]
I was able to use live2d until the recent update with ST. Then whenever I open ST the live2d option from the extensions is not showing up. Is this intended or a bug? Should I reinstall both ST and extras to see it? I git pulled for both and reinstalled requirements-complete.txt for extras but still not showing. Thanks

**Comment by SmoothBrainApe** [comment]
I deleted ST and reinstalled from git clone now it works. Weird bug. Thanks. I used --talkinghead-gpu

**Comment by bigsk1** [comment]
I'm having same issue, was going to check it out and having no luck, only see live2d Image type,  

added to to existing setup  

python server.py --cuda --enable-modules=caption,chromadb,summarize,classify,sd,talkinghead --talkinghead-gpu --sd-remote-port 7861  

and also tried just 

python server.py --enable-modules=classify,talkinghead --talkinghead-gpu   

I have also since day one of running Silly Extras have had this "OPTIONS /api/live2d/start_talking HTTP/1.1" 404 -  "OPTIONS /api/live2d/stop_talking HTTP/1.1" 404 - 

I do have a talkinghead empty image box at the bottom of character Expressions and have add a photo per the example provided. Just can't get that Image Type Live2d to not be shown

**Comment by bigsk1** [comment]
> @bigsk1 I did a clean install of Extras in conda with Python 3.11 and requirements-complete, and the most recent version of SillyTavern. Everything worked. Based on your logs, you have an outdated version of SillyTavern.

Yep that was it, I thought I did a git pull on both SillyTavern and Extras but appently I didn't on Silly Tavern and once I did it now works, Thank you.
